openapi: 3.0.0
servers:
 - url: http://localhost:250
info:
  description: MO2O API V1
  version: "1.0.0"
  title: MO2O API V1
#  contact:
#    email: default@default.com
#  termsOfService: 'https://default_api.com/legal.html'
tags:
  - name: Beer
    description: Beer Services

paths:
  allOf:
    - $ref: './beer/paths.yaml'
components:
#  securitySchemes:
#     bearerAuth: # arbitrary name for the security scheme
#      type: http
#      scheme: bearer
#      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  responses:
    ConflictException:
      description: Conflict DomainException
      content:
        application/json:
          schema:
            type: object
            required:
              - class
              - code
              - message
            properties:
              class:
                type: string
                description: Action Not Allowed
                example: UserInvalidPermissionException
              code:
                type: integer
                description: Error code
                example: 409
              message:
                type: string
                description: Error Message
                example: 'User does not have permission'
    InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                description: Error code
                example: 500
              message:
                type: string
                description: Error Message
                example: 'Internal Error'

    ResourceNotFound:
      description: ResourceNotFoundException
      content:
        application/json:
          schema:
            type: object
            required:
              - Class
              - code
              - message
            properties:
              class:
                type: string
                description: Instance Short Name Exception
                example: ResourceNotFoundException
              code:
                type: integer
                description: Error code
                example: 404
              message:
                type: string
                description: Error Message
                example: 'Example Entity NotFound'
  parameters:
    
  schemas:
    beer:
      $ref: './beer/schemas.yaml'